### PR TITLE
Update of IT & EN languages for Top Ten Topics extension

### PR DESCRIPTION
**Pull request by Galixte**
Hi @bruninoit,

- Removes a language key replaced by a native common phpBB language key.
- Fixes typo.

Other PR related, here: https://github.com/bruninoit/toptentopics/pull/4.

### CODE REVIEW

**Comment by Galixte** [comment]
@bruninoit, please merge this.

**Comment by bruninoit** [comment]
Please resend it because "This branch has conflicts that must be resolved"

**Comment by Galixte** [comment]
Ok i will, take a few minutes, please.

**Comment by Galixte** [comment]
@bruninoit, it’s done, here: https://github.com/bruninoit/toptentopics/pull/6.

**Comment by bruninoit** [comment]
Yes, thanks

**Pull request closed without merging**
